sonar-operator:
  # -- component name
  name: sonar-operator
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  image:
    # -- EDP sonar-operator Docker image name. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/sonar-operator)
    repository: epamedp/sonar-operator
    # if not defined then .Chart.AppVersion is used
    # -- EDP sonar-operator Docker image tag. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/sonar-operator/tags)
    tag: 3.1.1
  imagePullPolicy: "IfNotPresent"

  resources:
    limits:
      memory: 192Mi
    requests:
      cpu: 50m
      memory: 64Mi

  # -- Additional volumes to be added to the pod
  extraVolumes: []
  #  - name: custom-ca
  #    secret:
  #      defaultMode: 420
  #      secretName: custom-ca

  # -- Additional volumeMounts to be added to the container
  extraVolumeMounts: []
  #  - name: custom-ca
  #    mountPath: /etc/ssl/certs/CA.crt
  #    readOnly: true
  #    subPath: CA.crt

# -- URL and secret name which use sonar operator for configuring sonar
sonarUrl: "https://sonar.eks-test.aws.main.edp.projects.epam.com"
sonarSecret: "sonar-admin-password"

# -- Integration with keycloak
oidc:
  enabled: false
  keycloakUrl: "https://idp.core.kuberocketci.io"
  keycloakRealm: "sandbox"

# This section enables configuration for using External Secrets Operator (ESO) as the secret manager.
# Prerequisite: Ensure that ESO is installed in the cluster.
# Refer to the EDP cluster add-on for ESO installation and setup:
# https://github.com/epam/edp-cluster-add-ons/tree/main/clusters/core/addons/external-secrets
#
# Ensure that you have created the necessary roles for ESO integration.
# Follow the detailed instructions here:
# https://docs.kuberocketci.io/docs/operator-guide/secrets-management/external-secrets-operator-integration#aws-parameter-store-scenario-in-kuberocketci
eso:
  # -- Install components of the ESO.
  enabled: true
  # -- Defines provider type. One of `aws` or `generic`.
  type: "aws"
  # -- Defines Secret Store name.
  secretStoreName: "aws-parameterstore"
  # -- Value name in AWS ParameterStore, AWS SecretsManager or other Secret Store.
  secretName: "/edp/eks-sandbox/addons/sonar-operator"
  # -- Role ARN for the ExternalSecretOperator to assume.
  roleArn: arn:aws:iam::093899590031:role/AWSIRSASandboxExternalSecretOperatorAccess
  # Defines Secret Store configuration. Used when eso.type is set to "generic".
  generic:
    secretStore:
      # -- Defines SecretStore provider configuration.
      providerConfig: {}
      #  gcpsm:
      #    projectID: "alphabet-123"
