apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: krakend
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  target:
    name: krakend
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /edp/eks-sandbox/addons/krakend-dn-test
